<div class="row">
	<div class="col-sm-12">
		<div class="panel">
			<div class="panel-heading">
				<h4><?php echo $user->nombre .' '.$user->apellido.' '.$user->materno ?></h4>
				<div class="options">
					<ul class="nav nav-tabs">
						<li class="active"><a data-toggle="tab" href="#domshortcuttiles"><i class="fa fa-users"></i></a></li>
						<li><a data-toggle="tab" href="#codeshortcuttiles"><i class="fa fa-code"></i></a></li>
					</ul>
				</div>
			</div>
			<?php echo $this->flashSession->output() ?>
			<div class="panel-body">
				<div class="tab-content">
					<div class="row">
						<div class="col-md-12">
							<form class="form-horizontal form-bordered" id="testForm" data-toggle="validator" action="" method="post" />
							<input type="hidden" name="id" id="id">
							<div class="form-group">
							<label class="col-md-4 control-label"><strong>Nombres y Apellidos:</strong></label>
								<div class="col-md-8" >
									<p class="form-control-static"><?php echo $user->nombre .' '.$user->apellido.' '.$user->materno ?></p>
								</div>
							</div>
							<div class="form-group">
							<label class="col-md-4 control-label"><strong>Cargo:</strong></label>
								<div class="col-md-8" >
									<p class="form-control-static"><?php echo $user->cargo ?></p>
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-4 control-label"><strong>Correo:</strong></label>
								<div class="col-md-8" >
									<p class="form-control-static"><a href=""><?php echo $user->email ?></a></p>
								</div>
							</div>
							<hr>
							<h4>Cambiar Contraseña</h4>
							<div class="form-group">
								<label class="col-md-4 control-label"><strong>Contraseña Actual:</strong></label>
								<div class="col-md-8" >
									<input id="password_actual" name="password_actual" class="form-control" type="password" placeholder="Contraseña Actual" required value="">
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-4 control-label"><strong>Nueva Contraseña:</strong></label>
								<div class="col-md-8" >
									<input id="password_nuevo" name="password_nuevo" class="form-control" type="password" placeholder="Contraseña Nuevo" required value="">
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-4 control-label"><strong>Repiter Nueva Contraseña:</strong></label>
								<div class="col-md-8" >
									<input id="password_repetir" name="password_repetir" class="form-control" type="password" placeholder="Contraseña Nuevo Repetir" required value="">
								</div>
							</div>
							<div class="modal-footer">
								<a href="/" class="btn btn-default">Cancelar</a>
								<button type="submit" class="btn btn-primary" id="Save">Guardar</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
