<div class="row">
	<div class="col-sm-12">
		<div class="panel">
			<ul class="breadcrumb breadcrumb-top">
				<li><a href="/">Inicio</a></li>
				<li><a href="/planpagos/">Control Plan de Pagos</a></li>
				<li class="active">Plan Pagos</li>
			</ul>
			<div class="panel-heading">
				<div class="row">
					<div class="col-md-8">
						<h3><?php echo $contratoproducto->razon_social ?>&nbsp; <b>Contrato Nro:</b> <?php echo $contratoproducto->contrato ?>  </h3>		
					</div>	
					<div class="col-md-4">
					<?php if ($contratoproducto->estado == 1) { ?>
							<span class="label label-primary pull-right"><?php echo $contratoproducto->valor_1 ?></span>
						<?php } elseif ($contratoproducto->estado ==2) { ?>
							<span class="label label-success pull-right"><?php echo $contratoproducto->valor_1 ?></span>
						<?php } else{ ?>
							<span class="label label-danger pull-right"><?php echo $contratoproducto->valor_1 ?></span>
						<?php }?>
					</div>
				</div>
			</div>
			<div class="panel panel-primary">
				<div class="panel-body">
					<div class="row">
						<div class="table-responsive">
							<table class="table table-vcenter table-striped">
							<tbody>
								<tr>
									<td><strong>Grupo:</strong> <?php echo $contratoproducto->grupo ?></td>
									<td><strong>Estación:</strong> Linea <?php echo $contratoproducto->linea. ' -> ' .$contratoproducto->estacion ?></td>
									<td><strong>Producto:</strong> <?php echo $contratoproducto->producto ?></td>
									<td><strong>Fecha Inicio:</strong> <?php echo date("d-m-Y",strtotime($contratoproducto->fecha_inicio)) ?></td>
									<td><strong>Fecha Finalización:</strong> <?php echo date("d-m-Y",strtotime($contratoproducto->fecha_fin))  ?></td>
								</tr>
							</tbody>
						</table>
					
							
						</div>

					</div>
					<!-- grid garantia y derecho de llave -->
					<div class="row">
						<div class="col-sm-6">
							<?php if ($contratoproducto->estado==1) { ?>
							<div class="row">
								<div class="col-md-12">
									<div class="pull-left">
										<button class="btn btn-sm btn-default" type="button" id="dep_garantia" tipo='1'><i class="fa fa-plus fa-fw"></i>Deposito Garantia</button>
										<button class="btn btn-sm btn-default" type="button" id="dep_derechollave" tipo='2'><i class="fa fa-plus fa-fw"></i>Deposito Derecho Llave</button>
									</div>
								</div>
							</div>	
							<?php } ?>
							
							<div id="jqxgrid_garantia" style="width: 100%;" ></div>

						</div>
						<div class="col-sm-6">
						<?php if ($contratoproducto->estado==1) { ?>
							<div class="row">
								<div class="col-md-12">
									<div class="pull-left">
									<button class="btn btn-sm btn-default" type="button" id="dev_garantia" tipo='3'><i class="fa fa-plus fa-fw"></i>Devolución Garantia</button>
									</div>
								</div>
							</div>
						<?php } ?>
							<div id="jqxgrid_devolucion" style="width: 100%;" ></div>
						</div>
					</div>
					<br>
					<!--  -->

					<div class="row">
						<div class="col-md-10">
							<?php if ($contratoproducto->estado==1) { ?>
							<div class="pull-left">
								<button class="btn btn-sm btn-primary" type="button" id="reg_deposito"><i class="fa fa-plus fa-fw"></i>Deposito</button>
								<button class="btn btn-sm btn-warning" type="button" id="edit"><i class="fa fa-pencil fa-fw"></i> Editar</button>
								<button class="btn btn-sm btn-danger" type="button" id="reg_deposito_mora"><i class="fa fa-plus fa-fw"></i> Deposito Mora</button>
							</div>
							<?php } ?>
							<div class="pull-right">
								<a href="/planpagos/reporte/<?php echo $contratoproducto->id ?>" class="btn btn-sm btn-primary"><i class="fa fa-download"></i> Reporte</a>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-10">
							<div id="jqxgrid" style="height: 550px; width: 100%;" ></div>
						</div>
						<div class="col-md-2">
							<div id="jqxlistbox"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Modal Editar deposito -->
<div class="modal fade bs-example-modal-lg" id="myModal_editdeposito" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<form class="form-horizontal" id="testForm_editdeposito" data-toggle="validator" action="" method="post" />
			<input type="hidden" name="contratoproducto_id" id="contratoproducto_id" value="<?php echo $contratoproducto->id ?>">			
			<input type="hidden" name="planpago_id" id="planpago_id" value="">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<!-- <h4 class="modal-title" id="titulo_deposito">Editar</h4> -->
			</div>
			<div class="modal-body" id="html_depositos">
				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<!-- <button type="submit" class="btn btn-primary" id="Save">Guardar</button> -->
			</div>
		</form>
	</div>
</div>
</div>
<!-- end  modal -->

<!-- Modal Registrar deposito -->
<div class="modal fade" id="myModal_deposito" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<form class="form-horizontal" id="testForm_deposito" data-toggle="validator" action="" method="post" />
			<input type="hidden" name="contratoproducto_id" id="contratoproducto_id" value="<?php echo $contratoproducto_id ?>">
			<input type="hidden" name="planpago_id" id="planpago_id" value="">
			<input type="hidden" name="tipo_deposito" id="tipo_deposito" value="">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title" id="titulo_deposito">Editar</h4>
			</div>
			<div class="modal-body">
				<div class="form-group">
					<label class="col-md-3 control-label">Fecha Deposito</label>
					<div class="col-md-9">
						<input type="text" id="fecha_deposito" name="fecha_deposito" class="form-control" data-date-format="dd-mm-yyyy" placeholder="dd-mm-yyyy" required/>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-3 control-label">Nro Deposito</label>
					<div class="col-md-9">
						<input type="text" name="nro_deposito" id="nro_deposito" class="form-control" placeholder="" required>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-3 control-label">Monto Depositado Bs.</label>
					<div class="col-md-9">
						<input type="text" name="monto_deposito" id="monto_deposito" class="form-control" placeholder="" required>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<button type="submit" class="btn btn-primary" id="Save">Guardar</button>
			</div>
		</form>
	</div>
</div>
</div>
<!-- end  modal -->

<!-- Modal Derecho llave -->
<div class="modal fade" id="myModal_derechollave" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<form class="form-horizontal" id="testForm_derechollave" data-toggle="validator" action="" method="post" />
			<input type="hidden" name="contratoproducto_id" id="contratoproducto_id" value="<?php echo $contratoproducto_id ?>">
			<input type="hidden" name="garantia_id" id="garantia_id" value="">
			<input type="hidden" name="tipo" id="tipo" value="">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title" id="titulo_derechollave">Editar</h4>
			</div>
			<div class="modal-body">
				<div class="form-group">
					<label class="col-md-3 control-label">Fecha Deposito</label>
					<div class="col-md-9">
						<input type="text" id="fecha_deposito_derechollave" name="fecha_deposito_derechollave" class="form-control" data-date-format="dd-mm-yyyy" placeholder="dd-mm-yyyy" required/>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-3 control-label">Nro Deposito</label>
					<div class="col-md-9">
						<input type="text" name="nro_deposito_derechollave" id="nro_deposito_derechollave" class="form-control" placeholder="" required>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-3 control-label">Monto Depositado Bs.</label>
					<div class="col-md-9">
						<input type="text" name="monto_deposito_derechollave" id="monto_deposito_derechollave" class="form-control" placeholder="" required>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<button type="submit" class="btn btn-primary" id="Save">Guardar</button>
			</div>
		</form>
	</div>
</div>
</div>
<!-- end  modal -->

<!-- Modal Garantia -->
<div class="modal fade" id="myModal_garantia" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<form class="form-horizontal" id="testForm_garantia" data-toggle="validator" action="" method="post" />
			<!-- <input type="hidden" name="garantia_id" id="garantia_id" value=""> -->
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title" id="titulo_garantia">Editar</h4>
			</div>
			<div class="modal-body">
				<div class="form-group">
					<label class="col-md-3 control-label">Fecha Deposito</label>
					<div class="col-md-9">
						<input type="text" id="fecha_deposito_garantia" name="fecha_deposito_garantia" class="form-control" data-date-format="dd-mm-yyyy" placeholder="dd-mm-yyyy" required/>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-3 control-label">Nro Deposito</label>
					<div class="col-md-9">
						<input type="text" name="nro_deposito_garantia" id="nro_deposito_garantia" class="form-control" placeholder="" required>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-3 control-label">Monto Depositado Bs.</label>
					<div class="col-md-9">
						<input type="text" name="monto_deposito_garantia" id="monto_deposito_garantia" class="form-control" placeholder="" required>
					</div>
				</div>
				<hr>
				<div class="form-group">
					<label class="col-md-3 control-label">Fecha Devolución</label>
					<div class="col-md-9">
						<input type="text" id="fecha_devolucion_garantia" name="fecha_devolucion_garantia" class="form-control" data-date-format="dd-mm-yyyy" placeholder="dd-mm-yyyy" />
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-3 control-label">Nro Devolución</label>
					<div class="col-md-9">
						<input type="text" name="nro_devolucion_garantia" id="nro_devolucion_garantia" class="form-control" placeholder="" >
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-3 control-label">Monto Devolución Bs.</label>
					<div class="col-md-9">
						<input type="text" name="monto_devolucion_garantia" id="monto_devolucion_garantia" class="form-control" placeholder="" >
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<button type="submit" class="btn btn-primary" id="Save">Guardar</button>
			</div>
		</form>
	</div>
</div>
</div>
<!-- end  modal -->
<style type="text/css">
	.datepicker{
		z-index:1151 !important;
	}
</style>