<div class="row">
	<div class="col-sm-12">
		<div class="panel">
			<ul class="breadcrumb breadcrumb-top">
				<li><a href="/">Inicio</a></li>
				<li class="active">Control Plan de Pagos</li>
			</ul>
			<div class="panel-heading">
				<h4>Control Plan de Pagos</h4>
				<div class="options">
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#domshortcuttiles"><i class="fa fa-users"></i></a></li>
                        <li><a data-toggle="tab" href="#codeshortcuttiles"><i class="fa fa-code"></i></a></li>
                    </ul>
                </div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="pull-left">
						<button class="btn btn-sm btn-primary" type="button" id="control_pagos"><i class="fa fa-plus fa-fw"></i>Control Pagos</button>
						<!-- <button class="btn btn-sm btn-warning" type="button" id="edit"><i class="fa fa-pencil fa-fw"></i> Editar</button>
						<button class="btn btn-sm btn-danger" type="button" id="delete"><i class="fa fa-trash-o fa-fw"></i> Eliminar</button> -->
					</div>
				</div>
			</div>
			
					<div class="row">
						<div class="col-md-12">
							<div id="jqxgrid" style="height: 550px; width: 100%;" ></div>
						</div>
					</div>
		</div>
	</div>
</div>