<?php
if (isset($_POST['username'])) {
    $user = $_POST['username'];
} else {
    $user = '';
}
?>
<!-- BEGIN ERROR BOX -->
<?php  echo $this->flashSession->output(); ?> 
<div class="alert alert-danger hide">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4>Error!</h4>
</div>


<div class="header clearfix">
    <div class="pull-left"><i class="fa fa-suitcase"></i> CONTRATACIONES</div>
    <!-- <a href="#"><i class="fa fa-suitcase"></i> <span>Contrataciones</span></a>  -->
</div>
<form id="loginform" method="post" action="">
    <div class="alert alert-warning no-radius no-margin padding-sm"><i class="fa fa-info-circle"></i> Por favor inicie sesión para ingresar al sistema</div>
    <div class="box-body padding-md">
        <div class="form-group">
            <input type="text" name="username" class="form-control" placeholder="Usuario"/>
        </div>
        <div class="form-group">
            <input type="password" name="password" class="form-control" placeholder="Contraseña"/>
        </div>          
        <!-- <div class="form-group">
                            <input type="checkbox" /> <small>Remember me</small>
                        </div>   -->        
        <div class="box-footer">
            <button type="submit" class="btn btn-success btn-block">Ingresar</button>  
        </div>
    </div>
</form>

