<div class="row">
	<div class="col-sm-12">
		<div class="panel">
			<ul class="breadcrumb breadcrumb-top">
				<li><a href="/">Inicio</a></li>
				<li><a href="/contratos/">Contratos</a></li>
				<li class="active">Agregar Productos</li>
			</ul>
			<div class="panel-heading">
				<h4>Contrato Nro <strong><?php echo $contrato->contrato ?></strong></h4>
				<div class="options">
					<ul class="nav nav-tabs">
						<li class="active"><a data-toggle="tab" href="#domshortcuttiles"><i class="fa fa-users"></i></a></li>
						<li><a data-toggle="tab" href="#codeshortcuttiles"><i class="fa fa-code"></i></a></li>
					</ul>
				</div>
			</div>
			<div class="panel-body">
				<div class="tab-content">
					<div class="row">
						<div class="col-md-12">
							<table class="table table-borderless table-striped">
								<tr>
									<td width="15%"><strong>Cliente Razón Social</strong></td>
									<td><?php echo $contrato->razon_social ?></td>
									<td><strong>Contrato Nro</strong></td>
									<td><?php echo $contrato->contrato ?></td>
									<td><strong>Fecha Contrato</strong></td>
									<td><?php echo date("d-m-Y",strtotime($contrato->fecha_contrato)) ?></td>

								</tr>
								<tr>
									<td><strong>Descripción</strong></td>
									<td colspan="5"><?php echo $contrato->descripcion ?></td>
								</tr>
							</table>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<?php echo $this->flashSession->output(); ?>
							<div id="divMsjeExito" class="msjs-alert" hidden="hidden">
								<button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
								<h5>
									<i class="fa fa-check-circle"></i>
									<!-- &Eacute;xito! -->
									<a class="alert-link" href="javascript:void(0)" id="aMsjeExito"></a>
								</h5>
								
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<div class="pull-right">
								<?php if (($user->nivel==2 || $user->nivel==1) && $contrato->estado==1) { ?>
								<button class="btn btn-sm btn-default" type="button" id="definir_pp"><i class="fa fa-plus fa-fw"></i>Definir Plan Pagos</button>
								<button class="btn btn-sm btn-danger" type="button" id="quitar"><i class="fa fa-trash-o fa-fw"></i> Quitar Producto</button>
								<?php } ?>
								<button class="btn btn-sm btn-primary" type="button" id="ver_pp_todo"><i class="fa fa-plus fa-fw"></i>Ver Plan Pagos</button>
								
							</div>
						</div>
					</div> 

					<div class="row">
						<div class="col-md-12">
							<div class="table-responsive">
								<div id="jqxgrid_cp" style="height: 200px;" ></div>
							</div>
						</div>
					</div>
					<br>
					
					<?php if (($user->nivel==2 || $user->nivel==1) && $contrato->estado==1) { ?>
					<div class="row">
						<div class="col-md-12">
							<div class="pull-right">
								<button class="btn btn-sm btn-primary" type="button" id="add_contrato"><i class="fa fa-plus fa-fw"></i>Añadir a Contrato</button>
							</div>
						</div>
					</div> 
					<?php } ?>
					<div class="row">
						<div class="col-md-12">
							<div id="jqxgrid" style="height: 550px; width: 100%;" ></div>
						</div>
					</div>
				</div>
				

			</div>
		</div>
	</div>
</div>



<!-- Modal añadir a contrato -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<form class="form-horizontal" id="testForm" data-toggle="validator" action="" method="post" />
			<input type="hidden" name="id" id="id">
			<input type="hidden" name="contrato_id" id="contrato_id" value="<?php echo $contrato->id ?>">
			<input type="hidden" name="tipo_pago" id="tipo_pago" value="<?php echo $contrato->tipo_pago ?>">
			<input type="hidden" name="producto_id" id="producto_id" value="">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title" id="titulo">Editar</h4>
			</div>
			<div class="modal-body">
				<div class="form-group">
					<label class="col-md-3 control-label">Estación</label>
					<div class="col-md-9">
						<input type="text" name="estacion" id="estacion" class="form-control" placeholder="" readonly>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-3 control-label">Grupo</label>
					<div class="col-md-9">
						<input type="text" name="grupo" id="grupo" class="form-control" placeholder="" readonly="">
					</div>
				</div>
				<div class="form-group" >
					<label class="col-md-3 control-label">Producto</label>
					<div class="col-md-9">
						<input type="text" name="producto" id="producto" class="form-control" placeholder="" readonly="">
					</div>
				</div>
				<div class="form-group" >
					<label class="col-md-3 control-label">Cantidad</label>
					<div class="col-md-9">
						<input type="number" name="cantidad" id="cantidad" class="form-control" placeholder="">
					</div>
				</div>

<!-- 				<div class="input-daterange" data-date-format="dd-mm-yyyy">
					<div class="form-group">
						<label class="col-md-3 control-label">Fecha Inicio</label>
						<div class="col-md-5">
							<input type="text" id="fecha_inicio" name="fecha_inicio" class="form-control input-datepicker-close text-center" placeholder="dd-mm-yyyy" />
						</div>
						<div class="col-md-4">
							<input type="text" name="hora_inicio" id="hora_inicio" class="form-control" placeholder="HH:mm" value="00:00" required>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-3 control-label">Fecha Inicio</label>
						<div class="col-md-5">
							<input type="text" id="fecha_fin" name="fecha_fin" class="form-control input-datepicker-close text-center" placeholder="dd-mm-yyyy" />
						</div>
						<div class="col-md-4">
							<input type="text" name="hora_fin" id="hora_fin" class="form-control" placeholder="HH:mm" value="00:00" required>
						</div>
					</div>
				</div> -->

				
				
				<div class="form-group" >
					<label class="col-md-3 control-label">Fecha Inicio</label>
					<div class="col-md-5">
						<input type="text" id="fecha_inicio" name="fecha_inicio" class="form-control" data-date-format="dd-mm-yyyy" placeholder="dd-mm-yyyy" required/>
					</div>
					<div class="col-md-4">
						<input type="text" name="hora_inicio" id="hora_inicio" class="form-control" placeholder="HH:mm" value="00:00" required>
					</div>
				</div>
				<div class="form-group" >
					<label class="col-md-3 control-label">Fecha Finalización</label>
					<div class="col-md-5">
						<input type="text" id="fecha_fin" name="fecha_fin" class="form-control" data-date-format="dd-mm-yyyy" placeholder="dd-mm-yyyy" required/>
					</div>
					<div class="col-md-4">
						<input type="text" name="hora_fin" id="hora_fin" class="form-control" placeholder="HH:mm" value="00:00" required>
					</div>
				</div>

				<div class="form-group" >
					<label class="col-md-3 control-label">Tipo Alquiler</label>
					<div class="col-md-9">
						<?php echo $tiempo ?>
					</div>
				</div>
				<div class="form-group" >
					<label class="col-md-3 control-label">Precio Bs. <span id='tiempo_text'></span></label>
					<div class="col-md-9">
						<input type="number" name="precio_unitario" id="precio_unitario" class="form-control" required title="campo obligatorio">
					</div>
				</div>
				<div class="form-group" >
					<label class="col-md-3 control-label">Total</label>
					<div class="col-md-9">
						<input type="text" id="total" name="total" class="form-control" readonly>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<button type="submit" class="btn btn-primary" id="Save">Guardar</button>
			</div>
		</form>
	</div>
</div>
</div>
<!-- end  modal -->


<!-- Modal ver plan de pagos -->
<div class="modal fade" id="myModal_verpp" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<form class="form-horizontal" id="testForm" data-toggle="validator" action="" method="post" />
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title" id="titulo_pp">Editar</h4>
			</div>
			<div class="modal-body">
				<div id="contenido_pp">
				</div>
			</div>

		</form>
	</div>
</div>
</div>
<!-- end  modal -->

<!-- Modal definir plan de pagos -->
<div class="modal fade" id="myModal_definir_pp" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<form class="form-horizontal" id="testForm" data-toggle="validator" action="" method="post" />
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title">Definir Plan de Pagos</h4>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-md-12">
						<div class="form-group">
							<button class="btn btn-xs btn-primary" type="button" id="add_pp"> <i class="fa fa-plus-circle"> Adicionar</i> </button>
							<div id="li_pp">

							</div>
						</div>                          	
					</div>
				</div>
			</div>
		</form>
	</div>
</div>
</div>
<!-- end  modal -->

<!-- Modal adicionar plan de pagos -->
<div class="modal fade" id="myModal_pp" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<form class="form-horizontal" id="testForm_pp" data-toggle="validator" action="" method="post" />
			<input type="hidden" name="planpago_id" id="planpago_id">
			<input type="hidden" name="contratoproducto_id" id="contratoproducto_id">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title" id="titulo_pp">Adicionar Plan de Pagos</h4>
			</div>
			<div class="modal-body">
				<div class="form-group">
					<label class="col-md-3 control-label">Fecha Programado</label>
					<div class="col-md-9">
						<input type="text" id="fecha_programado" name="fecha_programado" class="form-control" data-date-format="dd-mm-yyyy" placeholder="dd-mm-yyyy" required/>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-3 control-label">Monto Programado Bs.</label>
					<div class="col-md-9">
						<input type="number" name="monto_programado" id="monto_programado" class="form-control" required title="campo obligatorio">
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<button type="submit" class="btn btn-primary" id="Save">Guardar</button>
			</div>
		</form>
	</div>
</div>
</div>
<!-- end  modal -->

<style type="text/css">
	.datepicker{
		z-index:1151 !important;
	}
</style>

<script>!window.jQuery && document.write(unescape('%3Cscript src="/assets/js/vendor/jquery-1.11.0.min.js"%3E%3C/script%3E'));</script>
<script>$(function() { FormsValidation.init(); });</script>				

