<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <title>MT-EETC - Contrataciones</title>
        
        <!-- Maniac stylesheets -->
        <link rel="stylesheet" href="/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/css/font-awesome.min.css" />
        <link rel="stylesheet" href="/css/animate/animate.min.css" />
        <link rel="stylesheet" href="/css/bootstrapValidator/bootstrapValidator.min.css" />
        <link rel="stylesheet" href="/css/iCheck/all.css" />
        <link rel="stylesheet" href="/css/style.css" />
        
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="login fixed">
        <div class="wrapper animated flipInY">
            <div class="logo">
            <!-- <a href="#"><i class="fa fa-suitcase"></i> <span>Contrataciones</span></a> -->
             <img src="/assets/img/logo.png" alt="Mi Teleferico">
            </div>
            <div class="box">
            <?php  echo $this->view->getContent(); ?>
                
            </div>
            <div class="box-extra clearfix">
                <a href="#" class="pull-left btn btn-xs">Olvido su Contraseña?</a>
                <a href="register.html" class="pull-right btn  btn-xs">Registrar una Cuenta</a>
            </div>
            
            <footer>
                Copyright &copy; 2016 - DTI
            </footer>
        </div>
        
        <!-- Javascript -->
         <script src="js/plugins/jquery/jquery-1.10.2.min.js" type="text/javascript"></script>
        <script src="js/plugins/jquery-ui/jquery-ui-1.10.4.min.js" type="text/javascript"></script>
        
        <!-- Bootstrap -->
        <script src="js/plugins/bootstrap/bootstrap.min.js" type="text/javascript"></script>
        
        <!-- Interface -->
        <script src="js/plugins/pace/pace.min.js" type="text/javascript"></script>
        
        <!-- Forms -->
        <script src="js/plugins/bootstrapValidator/bootstrapValidator.min.js" type="text/javascript"></script>
        <script src="js/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
        <script type="text/javascript">
            //iCheck
            $("input[type='checkbox'], input[type='radio']").iCheck({
                checkboxClass: 'icheckbox_minimal',
                radioClass: 'iradio_minimal'
            });
            
            $(document).ready(function() {
                $('#loginform').bootstrapValidator({
                    message: 'El valor no es valido',
                    fields: {
                        username: {
                            message: 'El usuario no es valido',
                            validators: {
                                notEmpty: {
                                    message: 'Se requiere el nombre del usuario'
                                }
                            }
                        },
                        password: {
                            validators: {
                                notEmpty: {
                                    message: 'Se requiere la contraseña'
                                }
                            }
                        }
                    }
                });
            });
        </script>
    </body>
</html>